site_name: Firewall On Demand
#repo_url: https://github.com/grnet/flowspy/
repo_url: https://github.com/GEANT/FOD/
#site_author: Stavros Kroustouris
site_author: GÃ‰ANT4-3 WP8 T3
site_dir: static/site
docs_dir: doc
#theme: readthedocs
#pages:
nav:
    - 'Introduction': 'index.md'
    - 'Prerequisites': 'prerequisites/generic.md'
    - 'Installation':
        - 'v1.3': 
          - 'Generic': 'installation/v1.3/generic.md'
          - 'Debian': 'installation/v1.3/debian_wheezy.md'
          - 'Red Hat': 'installation/v1.3/redhat.md'
        - 'v1.7':
          - 'Generic': 'installation/v1.7/generic.md'
          - 'DEBIAN/UBUNTU': 'installation/v1.7/debian_ubuntu.md'
          - 'CentOS': 'installation/v1.7/centos.md'
          - 'Docker': 'installation/v1.7/docker.md'
          - 'Docker Extra for Testing': 'installation/v1.7/docker_extra.md'
    - 'Configuration': 
        - 'v1.3': 'configuration/configuration-v1.3.md'
        - 'v1.7': 'configuration/configuration-v1.7.md'
    - 'Administration and Usage': 
        - 'Basic Administration and Usage (v1.7)': 'administration_and_usage/basic_administration_and_usage-v1.7.md'
    - 'API': 
        - 'v1.3': 'api/api-v1.3.md'
        - 'v1.7': 'api/api-v1.7.md'
    - 'Development':
        - 'Design Overview': 'development/design-overview.md'

